//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agents()
        {
            this.product_agent = new HashSet<product_agent>();
            this.productsale = new HashSet<productsale>();
        }
    
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Электронная_почта_агента { get; set; }
        public string Телефон_агента { get; set; }
        public string Логотип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public string Приоритет { get; set; }
        public string Директор { get; set; }
        public long ИНН { get; set; }
        public int КПП { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_agent> product_agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productsale> productsale { get; set; }
    }
}
