//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsale
    {
        public int id { get; set; }
        public string prod { get; set; }
        public int agent { get; set; }
        public System.DateTime date_realize { get; set; }
        public int num_of_prod { get; set; }
    
        public virtual agents agents { get; set; }
    }
}
