USE [master]
GO
/****** Object:  Database [195bv]    Script Date: 13.09.2022 12:44:26 ******/
CREATE DATABASE [195bv]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'195bv', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\195bv.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'195bv_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\195bv_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [195bv] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [195bv].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [195bv] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [195bv] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [195bv] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [195bv] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [195bv] SET ARITHABORT OFF 
GO
ALTER DATABASE [195bv] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [195bv] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [195bv] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [195bv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [195bv] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [195bv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [195bv] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [195bv] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [195bv] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [195bv] SET  DISABLE_BROKER 
GO
ALTER DATABASE [195bv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [195bv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [195bv] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [195bv] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [195bv] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [195bv] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [195bv] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [195bv] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [195bv] SET  MULTI_USER 
GO
ALTER DATABASE [195bv] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [195bv] SET DB_CHAINING OFF 
GO
ALTER DATABASE [195bv] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [195bv] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [195bv] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [195bv] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [195bv] SET QUERY_STORE = OFF
GO
USE [195bv]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 13.09.2022 12:44:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[Code] [varchar](6) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[Patronymic] [varchar](50) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[Phone] [varchar](20) NOT NULL,
	[Email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Country]    Script Date: 13.09.2022 12:44:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[Code] [varchar](3) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Flag] [binary](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelPhoto]    Script Date: 13.09.2022 12:44:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelPhoto](
	[ID] [int] NOT NULL,
	[Preview] [binary](50) NOT NULL,
	[PhotoPath] [varchar](200) NOT NULL,
 CONSTRAINT [PK_HotelPhoto] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Service]    Script Date: 13.09.2022 12:44:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Service](
	[ID] [int] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[PartnerID] [int] NOT NULL,
	[HotelID] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Service] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ServiceByTour]    Script Date: 13.09.2022 12:44:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ServiceByTour](
	[ID] [int] NOT NULL,
	[ServiceID] [int] NOT NULL,
	[IsControl] [char](1) NULL,
 CONSTRAINT [PK_ServiceByTour] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [195bv] SET  READ_WRITE 
GO
