//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientID { get; set; }
        public string Email { get; set; }
        public string fio { get; set; }
        public string Adress { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PassCode { get; set; }
        public int PassNumber { get; set; }
        public string Password { get; set; }
    }
}
