//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public int CostPerHour { get; set; }
        public int AmountOfItem { get; set; }
        public int ItemTypeID { get; set; }
    
        public virtual ItemTypes ItemTypes { get; set; }
    }
}
