//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActioRusApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int ItemID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
