//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActioRusApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        public int EmpID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
