//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActioRusApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterHistory
    {
        public int EnterID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Success { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
